'use client';
import './globals.css';
import Header from '@/components/Header';
import HeaderDefault from '@/components/HeaderDefault';
import Footer from '@/components/Footer';
import { usePathname } from 'next/navigation';
import { Noto_Sans_JP, Modak, Fugaz_One } from 'next/font/google';


export const noto = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  display: 'swap',
  variable: '--font-noto',
});

export const modak = Modak({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-modak',
});

export const fugaz = Fugaz_One({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-fugaz',
});

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isHomePage = pathname === '/';
  return (
    <html lang="en" className={`${noto.variable} ${modak.variable} ${fugaz.variable}`}>
      <body suppressHydrationWarning>
           <HeaderDefault />
          {children}
          <Footer />
      </body>
    </html>
  );
}
